name: Daily Photo Bot

on:
  schedule:
    # Run daily at 7:15 AM UTC+3
    - cron: '15 4 * * *'
  workflow_dispatch:  # Allow manual triggers for testing

jobs:
  send-daily-photo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run whatsapp bot
        env:
          WHATSAPP_API_TOKEN: ${{ secrets.WHATSAPP_API_TOKEN }}
          WHATSAPP_PHONE_NUMBER_ID: ${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}
          RECEIVER_NUMBER: ${{ secrets.RECEIVER_NUMBER }}
        run: uv run --frozen whatsapp-bot
