name: Daily Photo Bot

on:
  schedule:
    # Run daily at 8:00 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allow manual triggers for testing

jobs:
  send-daily-photo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install -e .

      - name: Run photo bot
        env:
          WHATSAPP_API_TOKEN: ${{ secrets.WHATSAPP_API_TOKEN }}
          WHATSAPP_PHONE_NUMBER_ID: ${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}
          RECEIVER_NUMBER: ${{ secrets.RECEIVER_NUMBER }}
        run: photos-bot --send 
